name: ci

on:
  push:

jobs:
  ios-integration-test:
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [macos-12, macos-13]
        a: [1, 2, 3]
      fail-fast: false
    steps:
      - uses: actions/checkout@3df4ab11eba7bda6032a0b82a6bb43b11571feac

      - name: Install Flutter
        uses: subosito/flutter-action@48cafc24713cca54bbe03cdc3a423187d413aafa

      - uses: futureware-tech/simulator-action@736249ceb5ed7916224ed6b6d3c3582fd8049deb
        id: simulator
        with:
          model: "iPhone 14"

      - name: Run integration tests
        env:
          SIMULATOR_UDID: ${{ steps.simulator.outputs.udid }}
        run: |
          # Using `flutter drive` instead of `flutter test` because of
          # https://github.com/flutter/flutter/issues/105913
            
          flutter drive \
            --driver=test_driver/integration_test.dart \
            --target=integration_test/widget_test.dart \
            -d $SIMULATOR_UDID
